<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\District;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        District::insert([
            array('id' => 1, 'name' => 'Abana','city_id' => 37),
            array('id' => 2, 'name' => 'Acıgöl','city_id' => 50),
            array('id' => 3, 'name' => 'Acıpayam','city_id' => 20),
            array('id' => 4, 'name' => 'Adaklı','city_id' => 12),
            array('id' => 5, 'name' => 'Adalar','city_id' => 34),
            array('id' => 6, 'name' => 'Adapazarı','city_id' => 54),
            array('id' => 7, 'name' => 'Adıyaman','city_id' => 2),
            array('id' => 8, 'name' => 'Adilcevaz','city_id' => 13),
            array('id' => 9, 'name' => 'Afşin','city_id' => 46),
            array('id' => 10, 'name' => 'Afyonkarahisar','city_id' => 3),
            array('id' => 11, 'name' => 'Ağaçören','city_id' => 68),
            array('id' => 12, 'name' => 'Ağın','city_id' => 23),
            array('id' => 13, 'name' => 'Ağlasun','city_id' => 15),
            array('id' => 14, 'name' => 'Ağlı','city_id' => 37),
            array('id' => 15, 'name' => 'Ağrı','city_id' => 4),
            array('id' => 16, 'name' => 'Ahırlı','city_id' => 42),
            array('id' => 17, 'name' => 'Ahlat','city_id' => 13),
            array('id' => 18, 'name' => 'Ahmetli','city_id' => 45),
            array('id' => 19, 'name' => 'Akçaabat','city_id' => 61),
            array('id' => 20, 'name' => 'Akçadağ','city_id' => 44),
            array('id' => 21, 'name' => 'Akçakale','city_id' => 63),
            array('id' => 22, 'name' => 'Akçakent','city_id' => 40),
            array('id' => 23, 'name' => 'Akçakoca','city_id' => 81),
            array('id' => 24, 'name' => 'Akdağmadeni','city_id' => 66),
            array('id' => 25, 'name' => 'Akdeniz','city_id' => 33),
            array('id' => 26, 'name' => 'Akhisar','city_id' => 45),
            array('id' => 27, 'name' => 'Akıncılar','city_id' => 58),
            array('id' => 28, 'name' => 'Akkışla','city_id' => 38),
            array('id' => 29, 'name' => 'Akkuş','city_id' => 52),
            array('id' => 30, 'name' => 'Akören','city_id' => 42),
            array('id' => 31, 'name' => 'Akpınar','city_id' => 40),
            array('id' => 32, 'name' => 'Aksaray','city_id' => 68),
            array('id' => 33, 'name' => 'Akseki','city_id' => 7),
            array('id' => 34, 'name' => 'Aksu','city_id' => 7),
            array('id' => 35, 'name' => 'Aksu','city_id' => 32),
            array('id' => 36, 'name' => 'Akşehir','city_id' => 42),
            array('id' => 37, 'name' => 'Akyaka','city_id' => 36),
            array('id' => 38, 'name' => 'Akyazı','city_id' => 54),
            array('id' => 39, 'name' => 'Akyurt','city_id' => 6),
            array('id' => 40, 'name' => 'Alaca','city_id' => 19),
            array('id' => 41, 'name' => 'Alacakaya','city_id' => 23),
            array('id' => 42, 'name' => 'Alaçam','city_id' => 55),
            array('id' => 43, 'name' => 'Aladağ','city_id' => 1),
            array('id' => 44, 'name' => 'Alanya','city_id' => 7),
            array('id' => 45, 'name' => 'Alaplı','city_id' => 67),
            array('id' => 46, 'name' => 'Alaşehir','city_id' => 45),
            array('id' => 47, 'name' => 'Aliağa','city_id' => 35),
            array('id' => 48, 'name' => 'Almus','city_id' => 60),
            array('id' => 49, 'name' => 'Alpu','city_id' => 26),
            array('id' => 50, 'name' => 'Altıeylül','city_id' => 10),
            array('id' => 51, 'name' => 'Altındağ','city_id' => 6),
            array('id' => 52, 'name' => 'Altınekin','city_id' => 42),
            array('id' => 53, 'name' => 'Altınordu','city_id' => 52),
            array('id' => 54, 'name' => 'Altınova','city_id' => 77),
            array('id' => 55, 'name' => 'Altınözü','city_id' => 31),
            array('id' => 56, 'name' => 'Altıntaş','city_id' => 43),
            array('id' => 57, 'name' => 'Altınyayla','city_id' => 15),
            array('id' => 58, 'name' => 'Altınyayla','city_id' => 58),
            array('id' => 59, 'name' => 'Altunhisar','city_id' => 51),
            array('id' => 60, 'name' => 'Alucra','city_id' => 28),
            array('id' => 61, 'name' => 'Amasra','city_id' => 74),
            array('id' => 62, 'name' => 'Amasya','city_id' => 5),
            array('id' => 63, 'name' => 'Anamur','city_id' => 33),
            array('id' => 64, 'name' => 'Andırın','city_id' => 46),
            array('id' => 65, 'name' => 'Antakya','city_id' => 31),
            array('id' => 66, 'name' => 'Araban','city_id' => 27),
            array('id' => 67, 'name' => 'Araç','city_id' => 37),
            array('id' => 68, 'name' => 'Araklı','city_id' => 61),
            array('id' => 69, 'name' => 'Aralık','city_id' => 76),
            array('id' => 70, 'name' => 'Arapgir','city_id' => 44),
            array('id' => 71, 'name' => 'Ardahan','city_id' => 75),
            array('id' => 72, 'name' => 'Ardanuç','city_id' => 8),
            array('id' => 73, 'name' => 'Ardeşen','city_id' => 53),
            array('id' => 74, 'name' => 'Arguvan','city_id' => 44),
            array('id' => 75, 'name' => 'Arhavi','city_id' => 8),
            array('id' => 76, 'name' => 'Arıcak','city_id' => 23),
            array('id' => 77, 'name' => 'Arifiye','city_id' => 54),
            array('id' => 78, 'name' => 'Armutlu','city_id' => 77),
            array('id' => 79, 'name' => 'Arnavutköy','city_id' => 34),
            array('id' => 80, 'name' => 'Arpaçay','city_id' => 36),
            array('id' => 81, 'name' => 'Arsin','city_id' => 61),
            array('id' => 82, 'name' => 'Arsuz','city_id' => 31),
            array('id' => 83, 'name' => 'Artova','city_id' => 60),
            array('id' => 84, 'name' => 'Artuklu','city_id' => 47),
            array('id' => 85, 'name' => 'Artvin','city_id' => 8),
            array('id' => 86, 'name' => 'Asarcık','city_id' => 55),
            array('id' => 87, 'name' => 'Aslanapa','city_id' => 43),
            array('id' => 88, 'name' => 'Aşkale','city_id' => 25),
            array('id' => 89, 'name' => 'Atabey','city_id' => 32),
            array('id' => 90, 'name' => 'Atakum','city_id' => 55),
            array('id' => 91, 'name' => 'Ataşehir','city_id' => 34),
            array('id' => 92, 'name' => 'Atkaracalar','city_id' => 18),
            array('id' => 93, 'name' => 'Avanos','city_id' => 50),
            array('id' => 94, 'name' => 'Avcılar','city_id' => 34),
            array('id' => 95, 'name' => 'Ayancık','city_id' => 57),
            array('id' => 96, 'name' => 'Ayaş','city_id' => 6),
            array('id' => 97, 'name' => 'Aybastı','city_id' => 52),
            array('id' => 98, 'name' => 'Aydıncık','city_id' => 33),
            array('id' => 99, 'name' => 'Aydıncık','city_id' => 66),
            array('id' => 100,'name' => 'Aydıntepe','city_id' => 69),
            array('id' => 101,'name' => 'Ayrancı','city_id' => 70),
            array('id' => 102,'name' => 'Ayvacık','city_id' => 17),
            array('id' => 103,'name' => 'Ayvacık','city_id' => 55),
            array('id' => 104,'name' => 'Ayvalık','city_id' => 10),
            array('id' => 105,'name' => 'Azdavay','city_id' => 37),
            array('id' => 106,'name' => 'Aziziye','city_id' => 25),
            array('id' => 107,'name' => 'Babadağ','city_id' => 20),
            array('id' => 108,'name' => 'Babaeski','city_id' => 39),
            array('id' => 109,'name' => 'Bafra','city_id' => 55),
            array('id' => 110,'name' => 'Bağcılar','city_id' => 34),
            array('id' => 111,'name' => 'Bağlar','city_id' => 21),
            array('id' => 112,'name' => 'Bahçe','city_id' => 80),
            array('id' => 113,'name' => 'Bahçelievler','city_id' => 34),
            array('id' => 114,'name' => 'Bahçesaray','city_id' => 65),
            array('id' => 115,'name' => 'Bahşili','city_id' => 71),
            array('id' => 116,'name' => 'Bakırköy','city_id' => 34),
            array('id' => 117,'name' => 'Baklan','city_id' => 20),
            array('id' => 118,'name' => 'Bala','city_id' => 6),
            array('id' => 119,'name' => 'Balçova','city_id' => 35),
            array('id' => 120,'name' => 'Balışeyh','city_id' => 71),
            array('id' => 121,'name' => 'Balya','city_id' => 10),
            array('id' => 122,'name' => 'Banaz','city_id' => 64),
            array('id' => 123,'name' => 'Bandırma','city_id' => 10),
            array('id' => 124,'name' => 'Bartın','city_id' => 74),
            array('id' => 125,'name' => 'Baskil','city_id' => 23),
            array('id' => 126,'name' => 'Başakşehir','city_id' => 34),
            array('id' => 127,'name' => 'Başçiftlik','city_id' => 60),
            array('id' => 128,'name' => 'Başiskele','city_id' => 41),
            array('id' => 129,'name' => 'Başkale','city_id' => 65),
            array('id' => 130,'name' => 'Başmakçı','city_id' => 3),
            array('id' => 131,'name' => 'Başyayla','city_id' => 70),
            array('id' => 132,'name' => 'Batman','city_id' => 72),
            array('id' => 133,'name' => 'Battalgazi','city_id' => 44),
            array('id' => 134,'name' => 'Bayat','city_id' => 3),
            array('id' => 135,'name' => 'Bayat','city_id' => 19),
            array('id' => 136,'name' => 'Bayburt','city_id' => 69),
            array('id' => 137,'name' => 'Bayındır','city_id' => 35),
            array('id' => 138,'name' => 'Baykan','city_id' => 56),
            array('id' => 139,'name' => 'Bayraklı','city_id' => 35),
            array('id' => 140,'name' => 'Bayramiç','city_id' => 17),
            array('id' => 141,'name' => 'Bayramören','city_id' => 18),
            array('id' => 142,'name' => 'Bayrampaşa','city_id' => 34),
            array('id' => 143,'name' => 'Bekilli','city_id' => 20),
            array('id' => 144,'name' => 'Belen','city_id' => 31),
            array('id' => 145,'name' => 'Bergama','city_id' => 35),
            array('id' => 146,'name' => 'Besni','city_id' => 2),
            array('id' => 147,'name' => 'Beşikdüzü','city_id' => 61),
            array('id' => 148,'name' => 'Beşiktaş','city_id' => 34),
            array('id' => 149,'name' => 'Beşiri','city_id' => 72),
            array('id' => 150,'name' => 'Beyağaç','city_id' => 20),
            array('id' => 151,'name' => 'Beydağ','city_id' => 35),
            array('id' => 152,'name' => 'Beykoz','city_id' => 34),
            array('id' => 153,'name' => 'Beylikdüzü','city_id' => 34),
            array('id' => 154,'name' => 'Beylikova','city_id' => 26),
            array('id' => 155,'name' => 'Beyoğlu','city_id' => 34),
            array('id' => 156,'name' => 'Beypazarı','city_id' => 6),
            array('id' => 157,'name' => 'Beyşehir','city_id' => 42),
            array('id' => 158,'name' => 'Beytüşşebap','city_id' => 73),
            array('id' => 159,'name' => 'Biga','city_id' => 17),
            array('id' => 160,'name' => 'Bigadiç','city_id' => 10),
            array('id' => 161,'name' => 'Bilecik','city_id' => 11),
            array('id' => 162,'name' => 'Bingöl','city_id' => 12),
            array('id' => 163,'name' => 'Birecik','city_id' => 63),
            array('id' => 164,'name' => 'Bismil','city_id' => 21),
            array('id' => 165,'name' => 'Bitlis','city_id' => 13),
            array('id' => 166,'name' => 'Bodrum','city_id' => 48),
            array('id' => 167,'name' => 'Boğazkale','city_id' => 19),
            array('id' => 168,'name' => 'Boğazlıyan','city_id' => 66),
            array('id' => 169,'name' => 'Bolu','city_id' => 14),
            array('id' => 170,'name' => 'Bolvadin','city_id' => 3),
            array('id' => 171,'name' => 'Bor','city_id' => 51),
            array('id' => 172,'name' => 'Borçka','city_id' => 8),
            array('id' => 173,'name' => 'Bornova','city_id' => 351),
            array('id' => 174,'name' => 'Boyabat','city_id' => 57),
            array('id' => 175,'name' => 'Bozcaada','city_id' => 17),
            array('id' => 176,'name' => 'Bozdoğan','city_id' => 9),
            array('id' => 177,'name' => 'Bozkır','city_id' => 42),
            array('id' => 178,'name' => 'Bozkurt','city_id' => 20),
            array('id' => 179,'name' => 'Bozkurt','city_id' => 37),
            array('id' => 180,'name' => 'Bozova','city_id' => 63),
            array('id' => 181,'name' => 'Boztepe','city_id' => 40),
            array('id' => 182,'name' => 'Bozüyük','city_id' => 11),
            array('id' => 183,'name' => 'Bozyazı','city_id' => 33),
            array('id' => 184,'name' => 'Buca','city_id' => 35),
            array('id' => 185,'name' => 'Bucak','city_id' => 15),
            array('id' => 186,'name' => 'Buharkent','city_id' => 9),
            array('id' => 187,'name' => 'Bulancak','city_id' => 28),
            array('id' => 188,'name' => 'Bulanık','city_id' => 49),
            array('id' => 189,'name' => 'Buldan','city_id' => 20),
            array('id' => 190,'name' => 'Burdur','city_id' => 15),
            array('id' => 191,'name' => 'Burhaniye','city_id' => 10),
            array('id' => 192,'name' => 'Bünyan','city_id' => 38),
            array('id' => 193,'name' => 'Büyükçekmece','city_id' => 34),
            array('id' => 194,'name' => 'Büyükorhan','city_id' => 16),
            array('id' => 195,'name' => 'Canik','city_id' => 55),
            array('id' => 196,'name' => 'Ceyhan','city_id' => 1),
            array('id' => 197,'name' => 'Ceylanpınar','city_id' => 63),
            array('id' => 198,'name' => 'Cide','city_id' => 37),
            array('id' => 199,'name' => 'Cihanbeyli','city_id' => 42),
            array('id' => 200,'name' => 'Cizre','city_id' => 73),
            array('id' => 201,'name' => 'Cumayeri','city_id' => 81),
            array('id' => 202,'name' => 'Çağlayancerit','city_id' => 46),
            array('id' => 203,'name' => 'Çal','city_id' => 20),
            array('id' => 204,'name' => 'Çaldıran','city_id' => 65),
            array('id' => 205,'name' => 'Çamardı','city_id' => 51),
            array('id' => 206,'name' => 'Çamaş','city_id' => 52),
            array('id' => 207,'name' => 'Çameli','city_id' => 20),
            array('id' => 208,'name' => 'Çamlıdere','city_id' => 6),
            array('id' => 209,'name' => 'Çamlıhemşin','city_id' => 53),
            array('id' => 210,'name' => 'Çamlıyayla','city_id' => 33),
            array('id' => 211,'name' => 'Çamoluk','city_id' => 28),
            array('id' => 212,'name' => 'Çan','city_id' => 17),
            array('id' => 213,'name' => 'Çanakçı','city_id' => 28),
            array('id' => 214,'name' => 'Çanakkale','city_id' => 17),
            array('id' => 215,'name' => 'Çandır','city_id' => 66),
            array('id' => 216,'name' => 'Çankaya','city_id' => 6),
            array('id' => 217,'name' => 'Çankırı','city_id' => 18),
            array('id' => 218,'name' => 'Çardak','city_id' => 20),
            array('id' => 219,'name' => 'Çarşamba','city_id' => 55),
            array('id' => 220,'name' => 'Çarşıbaşı','city_id' => 61),
            array('id' => 221,'name' => 'Çat','city_id' => 25),
            array('id' => 222,'name' => 'Çatak','city_id' => 65),
            array('id' => 223,'name' => 'Çatalca','city_id' => 34),
            array('id' => 224,'name' => 'Çatalpınar','city_id' => 52),
            array('id' => 225,'name' => 'Çatalzeytin','city_id' => 37),
            array('id' => 226,'name' => 'Çavdarhisar','city_id' => 43),
            array('id' => 227,'name' => 'Çavdır','city_id' => 15),
            array('id' => 228,'name' => 'Çay','city_id' => 3),
            array('id' => 229,'name' => 'Çaybaşı','city_id' => 52),
            array('id' => 230,'name' => 'Çaycuma','city_id' => 67),
            array('id' => 231,'name' => 'Çayeli','city_id' => 53),
            array('id' => 232,'name' => 'Çayıralan','city_id' => 66),
            array('id' => 233,'name' => 'Çayırlı','city_id' => 24),
            array('id' => 234,'name' => 'Çayırova','city_id' => 41),
            array('id' => 235,'name' => 'Çaykara','city_id' => 61),
            array('id' => 236,'name' => 'Çekerek','city_id' => 66),
            array('id' => 237,'name' => 'Çekmeköy','city_id' => 34),
            array('id' => 238,'name' => 'Çelebi','city_id' => 71),
            array('id' => 239,'name' => 'Çelikhan','city_id' => 2),
            array('id' => 240,'name' => 'Çeltik','city_id' => 42),
            array('id' => 241,'name' => 'Çeltikçi','city_id' => 15),
            array('id' => 242,'name' => 'Çemişgezek','city_id' => 62),
            array('id' => 243,'name' => 'Çerkeş','city_id' => 18),
            array('id' => 244,'name' => 'Çerkezköy','city_id' => 59),
            array('id' => 245,'name' => 'Çermik','city_id' => 21),
            array('id' => 246,'name' => 'Çeşme','city_id' => 35),
            array('id' => 247,'name' => 'Çıldır','city_id' => 75),
            array('id' => 248,'name' => 'Çınar','city_id' => 21),
            array('id' => 249,'name' => 'Çınarcık','city_id' => 77),
            array('id' => 250,'name' => 'Çiçekdağı','city_id' => 40),
            array('id' => 251,'name' => 'Çifteler','city_id' => 26),
            array('id' => 252,'name' => 'Çiftlik','city_id' => 51),
            array('id' => 253,'name' => 'Çiftlikköy','city_id' => 77),
            array('id' => 254,'name' => 'Çiğli','city_id' => 35),
            array('id' => 255,'name' => 'Çilimli','city_id' => 81),
            array('id' => 256,'name' => 'Çine','city_id' => 9),
            array('id' => 257,'name' => 'Çivril','city_id' => 20),
            array('id' => 258,'name' => 'Çobanlar','city_id' => 3),
            array('id' => 259,'name' => 'Çorlu','city_id' => 59),
            array('id' => 260,'name' => 'Çorum','city_id' => 19),
            array('id' => 261,'name' => 'Çubuk','city_id' => 6),
            array('id' => 262,'name' => 'Çukurca','city_id' => 30),
            array('id' => 263,'name' => 'Çukurova','city_id' => 1),
            array('id' => 264,'name' => 'Çumra','city_id' => 42),
            array('id' => 265,'name' => 'Çüngüş','city_id' => 21),
            array('id' => 266,'name' => 'Daday','city_id' => 37),
            array('id' => 267,'name' => 'Dalaman','city_id' => 48),
            array('id' => 268,'name' => 'Damal','city_id' => 75),
            array('id' => 269,'name' => 'Darende','city_id' => 44),
            array('id' => 270,'name' => 'Dargeçit','city_id' => 47),
            array('id' => 271,'name' => 'Darıca','city_id' => 41),
            array('id' => 272,'name' => 'Datça','city_id' => 48),
            array('id' => 273,'name' => 'Dazkırı','city_id' => 3),
            array('id' => 274,'name' => 'Defne','city_id' => 31),
            array('id' => 275,'name' => 'Delice','city_id' => 71),
            array('id' => 276,'name' => 'Demirci','city_id' => 45),
            array('id' => 277,'name' => 'Demirköy','city_id' => 39),
            array('id' => 278,'name' => 'Demirözü','city_id' => 69),
            array('id' => 279,'name' => 'Demre','city_id' => 7),
            array('id' => 280,'name' => 'Derbent','city_id' => 42),
            array('id' => 281,'name' => 'Derebucak','city_id' => 42),
            array('id' => 282,'name' => 'Dereli','city_id' => 28),
            array('id' => 283,'name' => 'Derepazarı','city_id' => 53),
            array('id' => 284,'name' => 'Derik','city_id' => 47),
            array('id' => 285,'name' => 'Derince','city_id' => 41),
            array('id' => 286,'name' => 'Derinkuyu','city_id' => 50),
            array('id' => 287,'name' => 'Dernekpazarı','city_id' => 61),
            array('id' => 288,'name' => 'Develi','city_id' => 38),
            array('id' => 289,'name' => 'Devrek','city_id' => 67),
            array('id' => 290,'name' => 'Devrekani','city_id' => 37),
            array('id' => 291,'name' => 'Dicle','city_id' => 21),
            array('id' => 292,'name' => 'Didim','city_id' => 9),
            array('id' => 293,'name' => 'Digor','city_id' => 36),
            array('id' => 294,'name' => 'Dikili','city_id' => 35),
            array('id' => 295,'name' => 'Dikmen','city_id' => 57),
            array('id' => 296,'name' => 'Dilovası','city_id' => 41),
            array('id' => 297,'name' => 'Dinar','city_id' => 3),
            array('id' => 298,'name' => 'Divriği','city_id' => 58),
            array('id' => 299,'name' => 'Diyadin','city_id' => 4),
            array('id' => 300,'name' => 'Dodurga','city_id' => 19),
            array('id' => 301,'name' => 'Doğanhisar','city_id' => 42),
            array('id' => 302,'name' => 'Doğankent','city_id' => 28),
            array('id' => 303,'name' => 'Doğanşar','city_id' => 58),
            array('id' => 304,'name' => 'Doğanşehir','city_id' => 44),
            array('id' => 305,'name' => 'Doğanyol','city_id' => 44),
            array('id' => 306,'name' => 'Doğanyurt','city_id' => 37),
            array('id' => 307,'name' => 'Doğubayazıt','city_id' => 4),
            array('id' => 308,'name' => 'Domaniç','city_id' => 43),
            array('id' => 309,'name' => 'Dörtdivan','city_id' => 14),
            array('id' => 310,'name' => 'Dörtyol','city_id' => 31),
            array('id' => 311,'name' => 'Döşemealtı','city_id' => 7),
            array('id' => 312,'name' => 'Dulkadiroğlu','city_id' => 46),
            array('id' => 313,'name' => 'Dumlupınar','city_id' => 43),
            array('id' => 314,'name' => 'Durağan','city_id' => 57),
            array('id' => 315,'name' => 'Dursunbey','city_id' => 10),
            array('id' => 316,'name' => 'Düzce','city_id' => 81),
            array('id' => 317,'name' => 'Düziçi','city_id' => 80),
            array('id' => 318,'name' => 'Düzköy','city_id' => 61),
            array('id' => 319,'name' => 'Eceabat','city_id' => 17),
            array('id' => 320,'name' => 'Edirne','city_id' => 22),
            array('id' => 321,'name' => 'Edremit','city_id' => 10),
            array('id' => 322,'name' => 'Edremit','city_id' => 65),
            array('id' => 323,'name' => 'Efeler','city_id' => 9),
            array('id' => 324,'name' => 'Eflani','city_id' => 78),
            array('id' => 325,'name' => 'Eğil','city_id' => 21),
            array('id' => 326,'name' => 'Eğirdir','city_id' => 32),
            array('id' => 327,'name' => 'Ekinözü','city_id' => 46),
            array('id' => 328,'name' => 'Elazığ','city_id' => 23),
            array('id' => 329,'name' => 'Elbeyli','city_id' => 79),
            array('id' => 330,'name' => 'Elbistan','city_id' => 46),
            array('id' => 331,'name' => 'Eldivan','city_id' => 18),
            array('id' => 332,'name' => 'Eleşkirt','city_id' => 4),
            array('id' => 333,'name' => 'Elmadağ','city_id' => 6),
            array('id' => 334,'name' => 'Elmalı','city_id' => 7),
            array('id' => 335,'name' => 'Emet','city_id' => 43),
            array('id' => 336,'name' => 'Emirdağ','city_id' => 3),
            array('id' => 337,'name' => 'Emirgazi','city_id' => 42),
            array('id' => 338,'name' => 'Enez','city_id' => 22),
            array('id' => 339,'name' => 'Erbaa','city_id' => 60),
            array('id' => 340,'name' => 'Erciş','city_id' => 65),
            array('id' => 341,'name' => 'Erdek','city_id' => 10),
            array('id' => 342,'name' => 'Erdemli','city_id' => 33),
            array('id' => 343,'name' => 'Ereğli','city_id' => 42),
            array('id' => 344,'name' => 'Ereğli','city_id' => 67),
            array('id' => 345,'name' => 'Erenler','city_id' => 54),
            array('id' => 346,'name' => 'Erfelek','city_id' => 57),
            array('id' => 347,'name' => 'Ergani','city_id' => 21),
            array('id' => 348,'name' => 'Ergene','city_id' => 59),
            array('id' => 349,'name' => 'Ermenek','city_id' => 70),
            array('id' => 350,'name' => 'Eruh','city_id' => 56),
            array('id' => 351,'name' => 'Erzin','city_id' => 31),
            array('id' => 352,'name' => 'Erzincan','city_id' => 24),
            array('id' => 353,'name' => 'Esenler','city_id' => 34),
            array('id' => 354,'name' => 'Esenyurt','city_id' => 34),
            array('id' => 355,'name' => 'Eskil','city_id' => 68),
            array('id' => 356,'name' => 'Eskipazar','city_id' => 78),
            array('id' => 357,'name' => 'Espiye','city_id' => 28),
            array('id' => 358,'name' => 'Eşme','city_id' => 64),
            array('id' => 359,'name' => 'Etimesgut','city_id' => 6),
            array('id' => 360,'name' => 'Evciler','city_id' => 3),
            array('id' => 361,'name' => 'Evren','city_id' => 6),
            array('id' => 362,'name' => 'Eynesil','city_id' => 28),
            array('id' => 363,'name' => 'Eyüp','city_id' => 34),
            array('id' => 364,'name' => 'Eyyübiye','city_id' => 63),
            array('id' => 365,'name' => 'Ezine','city_id' => 17),
            array('id' => 366,'name' => 'Fatih','city_id' => 34),
            array('id' => 367,'name' => 'Fatsa','city_id' => 52),
            array('id' => 368,'name' => 'Feke','city_id' => 1),
            array('id' => 369,'name' => 'Felahiye','city_id' => 38),
            array('id' => 370,'name' => 'Ferizli','city_id' => 54),
            array('id' => 371,'name' => 'Fethiye','city_id' => 48),
            array('id' => 372,'name' => 'Fındıklı','city_id' => 53),
            array('id' => 373,'name' => 'Finike','city_id' => 7),
            array('id' => 374,'name' => 'Foça','city_id' => 35),
            array('id' => 375,'name' => 'Gaziemir','city_id' => 35),
            array('id' => 376,'name' => 'Gaziosmanpaşa','city_id' => 34),
            array('id' => 377,'name' => 'Gazipaşa','city_id' => 7),
            array('id' => 378,'name' => 'Gebze','city_id' => 41),
            array('id' => 379,'name' => 'Gediz','city_id' => 43),
            array('id' => 380,'name' => 'Gelendost','city_id' => 32),
            array('id' => 381,'name' => 'Gelibolu','city_id' => 17),
            array('id' => 382,'name' => 'Gemerek','city_id' => 58),
            array('id' => 383,'name' => 'Gemlik','city_id' => 16),
            array('id' => 384,'name' => 'Genç','city_id' => 12),
            array('id' => 385,'name' => 'Gercüş','city_id' => 72),
            array('id' => 386,'name' => 'Gerede','city_id' => 14),
            array('id' => 387,'name' => 'Gerger','city_id' => 2),
            array('id' => 388,'name' => 'Germencik','city_id' => 9),
            array('id' => 389,'name' => 'Gerze','city_id' => 57),
            array('id' => 390,'name' => 'Gevaş','city_id' => 65),
            array('id' => 391,'name' => 'Geyve','city_id' => 54),
            array('id' => 392,'name' => 'Giresun','city_id' => 28),
            array('id' => 393,'name' => 'Gökçeada','city_id' => 17),
            array('id' => 394,'name' => 'Gökçebey','city_id' => 67),
            array('id' => 395,'name' => 'Göksun','city_id' => 46),
            array('id' => 396,'name' => 'Gölbaşı','city_id' => 2),
            array('id' => 397,'name' => 'Gölbaşı','city_id' => 6),
            array('id' => 398,'name' => 'Gölcük','city_id' => 41),
            array('id' => 399,'name' => 'Göle','city_id' => 75),
            array('id' => 400,'name' => 'Gölhisar','city_id' => 15),
            array('id' => 401,'name' => 'Gölköy','city_id' => 52),
            array('id' => 402,'name' => 'Gölmarmara','city_id' => 45),
            array('id' => 403,'name' => 'Gölova','city_id' => 58),
            array('id' => 404,'name' => 'Gölpazarı','city_id' => 11),
            array('id' => 405,'name' => 'Gölyaka','city_id' => 81),
            array('id' => 406,'name' => 'Gömeç','city_id' => 10),
            array('id' => 407,'name' => 'Gönen','city_id' => 10),
            array('id' => 408,'name' => 'Gönen','city_id' => 32),
            array('id' => 409,'name' => 'Gördes','city_id' => 45),
            array('id' => 410,'name' => 'Görele','city_id' => 28),
            array('id' => 411,'name' => 'Göynücek','city_id' => 5),
            array('id' => 412,'name' => 'Göynük','city_id' => 14),
            array('id' => 413,'name' => 'Güce','city_id' => 28),
            array('id' => 414,'name' => 'Güçlükonak','city_id' => 73),
            array('id' => 415,'name' => 'Güdül','city_id' => 6),
            array('id' => 416,'name' => 'Gülağaç','city_id' => 68),
            array('id' => 417,'name' => 'Gülnar','city_id' => 33),
            array('id' => 418,'name' => 'Gülşehir','city_id' => 50),
            array('id' => 419,'name' => 'Gülyalı','city_id' => 52),
            array('id' => 420,'name' => 'Gümüşhacıköy','city_id' => 5),
            array('id' => 421,'name' => 'Gümüşhane','city_id' => 29),
            array('id' => 422,'name' => 'Gümüşova','city_id' => 81),
            array('id' => 423,'name' => 'Gündoğmuş','city_id' => 7),
            array('id' => 424,'name' => 'Güney','city_id' => 20),
            array('id' => 425,'name' => 'Güneysınır','city_id' => 42),
            array('id' => 426,'name' => 'Güneysu','city_id' => 53),
            array('id' => 427,'name' => 'Güngören','city_id' => 34),
            array('id' => 428,'name' => 'Günyüzü','city_id' => 26),
            array('id' => 429,'name' => 'Gürgentepe','city_id' => 52),
            array('id' => 430,'name' => 'Güroymak','city_id' => 13),
            array('id' => 431,'name' => 'Gürpınar','city_id' => 65),
            array('id' => 432,'name' => 'Gürsu','city_id' => 16),
            array('id' => 433,'name' => 'Gürün','city_id' => 58),
            array('id' => 434,'name' => 'Güzelbahçe','city_id' => 35),
            array('id' => 435,'name' => 'Güzelyurt','city_id' => 68),
            array('id' => 436,'name' => 'Hacıbektaş','city_id' => 50),
            array('id' => 437,'name' => 'Hacılar','city_id' => 38),
            array('id' => 438,'name' => 'Hadim','city_id' => 42),
            array('id' => 439,'name' => 'Hafik','city_id' => 58),
            array('id' => 440,'name' => 'Hakkâri','city_id' => 30),
            array('id' => 441,'name' => 'Halfeti','city_id' => 63),
            array('id' => 442,'name' => 'Haliliye','city_id' => 63),
            array('id' => 443,'name' => 'Halkapınar','city_id' => 42),
            array('id' => 444,'name' => 'Hamamözü','city_id' => 5),
            array('id' => 445,'name' => 'Hamur','city_id' => 4),
            array('id' => 446,'name' => 'Han','city_id' => 26),
            array('id' => 447,'name' => 'Hanak','city_id' => 75),
            array('id' => 448,'name' => 'Hani','city_id' => 21),
            array('id' => 449,'name' => 'Hanönü','city_id' => 37),
            array('id' => 450,'name' => 'Harmancık','city_id' => 16),
            array('id' => 451,'name' => 'Harran','city_id' => 63),
            array('id' => 452,'name' => 'Hasanbeyli','city_id' => 80),
            array('id' => 453,'name' => 'Hasankeyf','city_id' => 72),
            array('id' => 454,'name' => 'Hasköy','city_id' => 49),
            array('id' => 455,'name' => 'Hassa','city_id' => 31),
            array('id' => 456,'name' => 'Havran','city_id' => 10),
            array('id' => 457,'name' => 'Havsa','city_id' => 22),
            array('id' => 458,'name' => 'Havza','city_id' => 55),
            array('id' => 459,'name' => 'Haymana','city_id' => 6),
            array('id' => 460,'name' => 'Hayrabolu','city_id' => 59),
            array('id' => 461,'name' => 'Hayrat','city_id' => 61),
            array('id' => 462,'name' => 'Hazro','city_id' => 21),
            array('id' => 463,'name' => 'Hekimhan','city_id' => 44),
            array('id' => 464,'name' => 'Hemşin','city_id' => 53),
            array('id' => 465,'name' => 'Hendek','city_id' => 54),
            array('id' => 466,'name' => 'Hınıs','city_id' => 25),
            array('id' => 467,'name' => 'Hilvan','city_id' => 63),
            array('id' => 468,'name' => 'Hisarcık','city_id' => 43),
            array('id' => 469,'name' => 'Hizan','city_id' => 13),
            array('id' => 470,'name' => 'Hocalar','city_id' => 3),
            array('id' => 471,'name' => 'Honaz','city_id' => 20),
            array('id' => 472,'name' => 'Hopa','city_id' => 8),
            array('id' => 473,'name' => 'Horasan','city_id' => 25),
            array('id' => 474,'name' => 'Hozat','city_id' => 62),
            array('id' => 475,'name' => 'Hüyük','city_id' => 42),
            array('id' => 476,'name' => 'Iğdır','city_id' => 76),
            array('id' => 477,'name' => 'Ilgaz','city_id' => 18),
            array('id' => 478,'name' => 'Ilgın','city_id' => 42),
            array('id' => 479,'name' => 'Isparta','city_id' => 32),
            array('id' => 480,'name' => 'İbradı','city_id' => 7),
            array('id' => 481,'name' => 'İdil','city_id' => 73),
            array('id' => 482,'name' => 'İhsangazi','city_id' => 37),
            array('id' => 483,'name' => 'İhsaniye','city_id' => 3),
            array('id' => 484,'name' => 'İkizce','city_id' => 52),
            array('id' => 485,'name' => 'İkizdere','city_id' => 53),
            array('id' => 486,'name' => 'İliç','city_id' => 24),
            array('id' => 487,'name' => 'İlkadım','city_id' => 55),
            array('id' => 488,'name' => 'İmamoğlu','city_id' => 1),
            array('id' => 489,'name' => 'İmranlı','city_id' => 58),
            array('id' => 490,'name' => 'İncesu','city_id' => 38),
            array('id' => 491,'name' => 'İncirliova','city_id' => 9),
            array('id' => 492,'name' => 'İnebolu','city_id' => 37),
            array('id' => 493,'name' => 'İnegöl','city_id' => 16),
            array('id' => 494,'name' => 'İnhisar','city_id' => 11),
            array('id' => 495,'name' => 'İnönü','city_id' => 26),
            array('id' => 496,'name' => 'İpekyolu','city_id' => 65),
            array('id' => 497,'name' => 'İpsala','city_id' => 22),
            array('id' => 498,'name' => 'İscehisar','city_id' => 3),
            array('id' => 499,'name' => 'İskenderun','city_id' => 31),
            array('id' => 500,'name' => 'İskilip','city_id' => 19),
            array('id' => 501,'name' => 'İslahiye','city_id' => 27),
            array('id' => 502,'name' => 'İspir','city_id' => 25),
            array('id' => 503,'name' => 'İvrindi','city_id' => 10),
            array('id' => 504,'name' => 'İyidere','city_id' => 53),
            array('id' => 505,'name' => 'İzmit','city_id' => 41),
            array('id' => 506,'name' => 'İznik','city_id' => 16),
            array('id' => 507,'name' => 'Kabadüz','city_id' => 52),
            array('id' => 508,'name' => 'Kabataş','city_id' => 52),
            array('id' => 509,'name' => 'Kadıköy','city_id' => 34),
            array('id' => 510,'name' => 'Kadınhanı','city_id' => 42),
            array('id' => 511,'name' => 'Kadışehri','city_id' => 66),
            array('id' => 512,'name' => 'Kadirli','city_id' => 80),
            array('id' => 513,'name' => 'Kağıthane','city_id' => 34),
            array('id' => 514,'name' => 'Kağızman','city_id' => 36),
            array('id' => 515,'name' => 'Kahta','city_id' => 2),
            array('id' => 516,'name' => 'Kale','city_id' => 20),
            array('id' => 517,'name' => 'Kale','city_id' => 44),
            array('id' => 518,'name' => 'Kalecik','city_id' => 6),
            array('id' => 519,'name' => 'Kalkandere','city_id' => 53),
            array('id' => 520,'name' => 'Kaman','city_id' => 40),
            array('id' => 521,'name' => 'Kandıra','city_id' => 41),
            array('id' => 522,'name' => 'Kangal','city_id' => 58),
            array('id' => 523,'name' => 'Kapaklı','city_id' => 59),
            array('id' => 524,'name' => 'Karabağlar','city_id' => 35),
            array('id' => 525,'name' => 'Karaburun','city_id' => 35),
            array('id' => 526,'name' => 'Karabük','city_id' => 78),
            array('id' => 527,'name' => 'Karacabey','city_id' => 16),
            array('id' => 528,'name' => 'Karacasu','city_id' => 9),
            array('id' => 529,'name' => 'Karaçoban','city_id' => 25),
            array('id' => 530,'name' => 'Karahallı','city_id' => 64),
            array('id' => 531,'name' => 'Karaisalı','city_id' => 1),
            array('id' => 532,'name' => 'Karakeçili','city_id' => 71),
            array('id' => 533,'name' => 'Karakoçan','city_id' => 23),
            array('id' => 534,'name' => 'Karakoyunlu','city_id' => 76),
            array('id' => 535,'name' => 'Karaköprü','city_id' => 63),
            array('id' => 536,'name' => 'Karaman','city_id' => 70),
            array('id' => 537,'name' => 'Karamanlı','city_id' => 15),
            array('id' => 538,'name' => 'Karamürsel','city_id' => 41),
            array('id' => 539,'name' => 'Karapınar','city_id' => 42),
            array('id' => 540,'name' => 'Karapürçek','city_id' => 54),
            array('id' => 541,'name' => 'Karasu','city_id' => 54),
            array('id' => 542,'name' => 'Karataş','city_id' => 1),
            array('id' => 543,'name' => 'Karatay','city_id' => 42),
            array('id' => 544,'name' => 'Karayazı','city_id' => 25),
            array('id' => 545,'name' => 'Karesi','city_id' => 10),
            array('id' => 546,'name' => 'Kargı','city_id' => 19),
            array('id' => 547,'name' => 'Karkamış','city_id' => 27),
            array('id' => 548,'name' => 'Karlıova','city_id' => 12),
            array('id' => 549,'name' => 'Karpuzlu','city_id' => 9),
            array('id' => 550,'name' => 'Kars','city_id' => 36),
            array('id' => 551,'name' => 'Karşıyaka','city_id' => 35),
            array('id' => 552,'name' => 'Kartal','city_id' => 34),
            array('id' => 553,'name' => 'Kartepe','city_id' => 41),
            array('id' => 554,'name' => 'Kastamonu','city_id' => 37),
            array('id' => 555,'name' => 'Kaş','city_id' => 7),
            array('id' => 556,'name' => 'Kavak','city_id' => 55),
            array('id' => 557,'name' => 'Kavaklıdere','city_id' => 48),
            array('id' => 558,'name' => 'Kayapınar','city_id' => 21),
            array('id' => 559,'name' => 'Kaynarca','city_id' => 54),
            array('id' => 560,'name' => 'Kaynaşlı','city_id' => 81),
            array('id' => 561,'name' => 'Kazan','city_id' => 6),
            array('id' => 562,'name' => 'Kazımkarabekir','city_id' => 70),
            array('id' => 563,'name' => 'Keban','city_id' => 23),
            array('id' => 564,'name' => 'Keçiborlu','city_id' => 32),
            array('id' => 565,'name' => 'Keçiören','city_id' => 6),
            array('id' => 566,'name' => 'Keles','city_id' => 16),
            array('id' => 567,'name' => 'Kelkit','city_id' => 29),
            array('id' => 568,'name' => 'Kemah','city_id' => 24),
            array('id' => 569,'name' => 'Kemaliye','city_id' => 24),
            array('id' => 570,'name' => 'Kemalpaşa','city_id' => 35),
            array('id' => 571,'name' => 'Kemer','city_id' => 7),
            array('id' => 572,'name' => 'Kemer','city_id' => 15),
            array('id' => 573,'name' => 'Kepez','city_id' => 7),
            array('id' => 574,'name' => 'Kepsut','city_id' => 10),
            array('id' => 575,'name' => 'Keskin','city_id' => 71),
            array('id' => 576,'name' => 'Kestel','city_id' => 16),
            array('id' => 577,'name' => 'Keşan','city_id' => 22),
            array('id' => 578,'name' => 'Keşap','city_id' => 28),
            array('id' => 579,'name' => 'Kıbrıscık','city_id' => 14),
            array('id' => 580,'name' => 'Kınık','city_id' => 35),
            array('id' => 581,'name' => 'Kırıkhan','city_id' => 31),
            array('id' => 582,'name' => 'Kırıkkale','city_id' => 71),
            array('id' => 583,'name' => 'Kırkağaç','city_id' => 45),
            array('id' => 584,'name' => 'Kırklareli','city_id' => 39),
            array('id' => 585,'name' => 'Kırşehir','city_id' => 40),
            array('id' => 586,'name' => 'Kızılcahamam','city_id' => 6),
            array('id' => 587,'name' => 'Kızılırmak','city_id' => 18),
            array('id' => 588,'name' => 'Kızılören','city_id' => 3),
            array('id' => 589,'name' => 'Kızıltepe','city_id' => 47),
            array('id' => 590,'name' => 'Kiğı','city_id' => 12),
            array('id' => 591,'name' => 'Kilimli','city_id' => 67),
            array('id' => 592,'name' => 'Kilis','city_id' => 79),
            array('id' => 593,'name' => 'Kiraz','city_id' => 35),
            array('id' => 594,'name' => 'Kocaali','city_id' => 54),
            array('id' => 595,'name' => 'Kocaköy','city_id' => 21),
            array('id' => 596,'name' => 'Kocasinan','city_id' => 38),
            array('id' => 597,'name' => 'Koçarlı','city_id' => 9),
            array('id' => 598,'name' => 'Kofçaz','city_id' => 39),
            array('id' => 599,'name' => 'Konak','city_id' => 35),
            array('id' => 600,'name' => 'Konyaaltı','city_id' => 7),
            array('id' => 601,'name' => 'Korgan','city_id' => 52),
            array('id' => 602,'name' => 'Korgun','city_id' => 18),
            array('id' => 603,'name' => 'Korkut','city_id' => 49),
            array('id' => 604,'name' => 'Korkuteli','city_id' => 7),
            array('id' => 605,'name' => 'Kovancılar','city_id' => 23),
            array('id' => 606,'name' => 'Koyulhisar','city_id' => 58),
            array('id' => 607,'name' => 'Kozaklı','city_id' => 50),
            array('id' => 608,'name' => 'Kozan','city_id' => 1),
            array('id' => 609,'name' => 'Kozlu','city_id' => 67),
            array('id' => 610,'name' => 'Kozluk','city_id' => 72),
            array('id' => 611,'name' => 'Köprübaşı','city_id' => 45),
            array('id' => 612,'name' => 'Köprübaşı','city_id' => 61),
            array('id' => 613,'name' => 'Köprüköy','city_id' => 25),
            array('id' => 614,'name' => 'Körfez','city_id' => 41),
            array('id' => 615,'name' => 'Köse','city_id' => 29),
            array('id' => 616,'name' => 'Köşk','city_id' => 9),
            array('id' => 617,'name' => 'Köyceğiz','city_id' => 48),
            array('id' => 618,'name' => 'Kula','city_id' => 45),
            array('id' => 619,'name' => 'Kulp','city_id' => 21),
            array('id' => 620,'name' => 'Kulu','city_id' => 42),
            array('id' => 621,'name' => 'Kuluncak','city_id' => 44),
            array('id' => 622,'name' => 'Kumlu','city_id' => 31),
            array('id' => 623,'name' => 'Kumluca','city_id' => 7),
            array('id' => 624,'name' => 'Kumru','city_id' => 52),
            array('id' => 625,'name' => 'Kurşunlu','city_id' => 18),
            array('id' => 626,'name' => 'Kurtalan','city_id' => 56),
            array('id' => 627,'name' => 'Kurucaşile','city_id' => 74),
            array('id' => 628,'name' => 'Kuşadası','city_id' => 9),
            array('id' => 629,'name' => 'Kuyucak','city_id' => 9),
            array('id' => 630,'name' => 'Küçükçekmece','city_id' => 34),
            array('id' => 631,'name' => 'Küre','city_id' => 37),
            array('id' => 632,'name' => 'Kürtün','city_id' => 29),
            array('id' => 633,'name' => 'Kütahya','city_id' => 43),
            array('id' => 634,'name' => 'Laçin','city_id' => 19),
            array('id' => 635,'name' => 'Ladik','city_id' => 55),
            array('id' => 636,'name' => 'Lalapaşa','city_id' => 22),
            array('id' => 637,'name' => 'Lapseki','city_id' => 17),
            array('id' => 638,'name' => 'Lice','city_id' => 21),
            array('id' => 639,'name' => 'Lüleburgaz','city_id' => 39),
            array('id' => 640,'name' => 'Maçka','city_id' => 61),
            array('id' => 641,'name' => 'Maden','city_id' => 23),
            array('id' => 642,'name' => 'Mahmudiye','city_id' => 26),
            array('id' => 643,'name' => 'Malazgirt','city_id' => 49),
            array('id' => 644,'name' => 'Malkara','city_id' => 59),
            array('id' => 645,'name' => 'Maltepe','city_id' => 34),
            array('id' => 646,'name' => 'Mamak','city_id' => 6),
            array('id' => 647,'name' => 'Manavgat','city_id' => 7),
            array('id' => 648,'name' => 'Manyas','city_id' => 10),
            array('id' => 649,'name' => 'Marmara','city_id' => 10),
            array('id' => 650,'name' => 'Marmaraereğlisi','city_id' => 59),
            array('id' => 651,'name' => 'Marmaris','city_id' => 48),
            array('id' => 652,'name' => 'Mazgirt','city_id' => 62),
            array('id' => 653,'name' => 'Mazıdağı','city_id' => 47),
            array('id' => 654,'name' => 'Mecitözü','city_id' => 19),
            array('id' => 655,'name' => 'Melikgazi','city_id' => 38),
            array('id' => 656,'name' => 'Menderes','city_id' => 35),
            array('id' => 657,'name' => 'Menemen','city_id' => 35),
            array('id' => 658,'name' => 'Mengen','city_id' => 14),
            array('id' => 659,'name' => 'Menteşe','city_id' => 48),
            array('id' => 660,'name' => 'Meram','city_id' => 42),
            array('id' => 661,'name' => 'Meriç','city_id' => 22),
            array('id' => 662,'name' => 'Merkezefendi','city_id' => 20),
            array('id' => 663,'name' => 'Merzifon','city_id' => 5),
            array('id' => 664,'name' => 'Mesudiye','city_id' => 52),
            array('id' => 665,'name' => 'Mezitli','city_id' => 33),
            array('id' => 666,'name' => 'Midyat','city_id' => 47),
            array('id' => 667,'name' => 'Mihalgazi','city_id' => 26),
            array('id' => 668,'name' => 'Mihalıççık','city_id' => 26),
            array('id' => 669,'name' => 'Milas','city_id' => 48),
            array('id' => 670,'name' => 'Mucur','city_id' => 40),
            array('id' => 671,'name' => 'Mudanya','city_id' => 16),
            array('id' => 672,'name' => 'Mudurnu','city_id' => 14),
            array('id' => 673,'name' => 'Muradiye','city_id' => 65),
            array('id' => 674,'name' => 'Muratlı','city_id' => 59),
            array('id' => 675,'name' => 'Muratpaşa','city_id' => 7),
            array('id' => 676,'name' => 'Murgul','city_id' => 8),
            array('id' => 677,'name' => 'Musabeyli','city_id' => 79),
            array('id' => 678,'name' => 'Mustafakemalpaşa','city_id' => 16),
            array('id' => 679,'name' => 'Muş','city_id' => 49),
            array('id' => 680,'name' => 'Mut','city_id' => 33),
            array('id' => 681,'name' => 'Mutki','city_id' => 13),
            array('id' => 682,'name' => 'Nallıhan','city_id' => 6),
            array('id' => 683,'name' => 'Narlıdere','city_id' => 35),
            array('id' => 684,'name' => 'Narman','city_id' => 25),
            array('id' => 685,'name' => 'Nazımiye','city_id' => 62),
            array('id' => 686,'name' => 'Nazilli','city_id' => 9),
            array('id' => 687,'name' => 'Nevşehir','city_id' => 50),
            array('id' => 688,'name' => 'Niğde','city_id' => 51),
            array('id' => 689,'name' => 'Niksar','city_id' => 60),
            array('id' => 690,'name' => 'Nilüfer','city_id' => 16),
            array('id' => 691,'name' => 'Nizip','city_id' => 27),
            array('id' => 692,'name' => 'Nurdağı','city_id' => 27),
            array('id' => 693,'name' => 'Nurhak','city_id' => 46),
            array('id' => 694,'name' => 'Nusaybin','city_id' => 47),
            array('id' => 695,'name' => 'Odunpazarı','city_id' => 26),
            array('id' => 696,'name' => 'Of','city_id' => 61),
            array('id' => 697,'name' => 'Oğuzeli','city_id' => 27),
            array('id' => 698,'name' => 'Oğuzlar','city_id' => 19),
            array('id' => 699,'name' => 'Oltu','city_id' => 25),
            array('id' => 700,'name' => 'Olur','city_id' => 25),
            array('id' => 701,'name' => 'Ondokuzmayıs','city_id' => 55),
            array('id' => 702,'name' => 'Onikişubat','city_id' => 46),
            array('id' => 703,'name' => 'Orhaneli','city_id' => 16),
            array('id' => 704,'name' => 'Orhangazi','city_id' => 16),
            array('id' => 705,'name' => 'Orta','city_id' => 18),
            array('id' => 706,'name' => 'Ortaca','city_id' => 48),
            array('id' => 707,'name' => 'Ortahisar','city_id' => 61),
            array('id' => 708,'name' => 'Ortaköy','city_id' => 68),
            array('id' => 709,'name' => 'Ortaköy','city_id' => 19),
            array('id' => 710,'name' => 'Osmancık','city_id' => 19),
            array('id' => 711,'name' => 'Osmaneli','city_id' => 11),
            array('id' => 712,'name' => 'Osmangazi','city_id' => 16),
            array('id' => 713,'name' => 'Osmaniye','city_id' => 80),
            array('id' => 714,'name' => 'Otlukbeli','city_id' => 24),
            array('id' => 715,'name' => 'Ovacık','city_id' => 78),
            array('id' => 716,'name' => 'Ovacık','city_id' => 62),
            array('id' => 717,'name' => 'Ödemiş','city_id' => 35),
            array('id' => 718,'name' => 'Ömerli','city_id' => 47),
            array('id' => 719,'name' => 'Özalp','city_id' => 65),
            array('id' => 720,'name' => 'Özvatan','city_id' => 38),
            array('id' => 721,'name' => 'Palandöken','city_id' => 25),
            array('id' => 722,'name' => 'Palu','city_id' => 23),
            array('id' => 723,'name' => 'Pamukkale','city_id' => 20),
            array('id' => 724,'name' => 'Pamukova','city_id' => 54),
            array('id' => 725,'name' => 'Pasinler','city_id' => 25),
            array('id' => 726,'name' => 'Patnos','city_id' => 4),
            array('id' => 727,'name' => 'Payas','city_id' => 31),
            array('id' => 728,'name' => 'Pazar','city_id' => 53),
            array('id' => 729,'name' => 'Pazar','city_id' => 60),
            array('id' => 730,'name' => 'Pazarcık','city_id' => 46),
            array('id' => 731,'name' => 'Pazarlar','city_id' => 43),
            array('id' => 732,'name' => 'Pazaryeri','city_id' => 11),
            array('id' => 733,'name' => 'Pazaryolu','city_id' => 25),
            array('id' => 734,'name' => 'Pehlivanköy','city_id' => 39),
            array('id' => 735,'name' => 'Pendik','city_id' => 34),
            array('id' => 736,'name' => 'Perşembe','city_id' => 52),
            array('id' => 737,'name' => 'Pertek','city_id' => 62),
            array('id' => 738,'name' => 'Pervari','city_id' => 56),
            array('id' => 739,'name' => 'Pınarbaşı','city_id' => 37),
            array('id' => 740,'name' => 'Pınarbaşı','city_id' => 38),
            array('id' => 741,'name' => 'Pınarhisar','city_id' => 39),
            array('id' => 742,'name' => 'Piraziz','city_id' => 28),
            array('id' => 743,'name' => 'Polateli','city_id' => 79),
            array('id' => 744,'name' => 'Polatlı','city_id' => 6),
            array('id' => 745,'name' => 'Posof','city_id' => 75),
            array('id' => 746,'name' => 'Pozantı','city_id' => 1),
            array('id' => 747,'name' => 'Pursaklar','city_id' => 6),
            array('id' => 748,'name' => 'Pülümür','city_id' => 62),
            array('id' => 749,'name' => 'Pütürge','city_id' => 44),
            array('id' => 750,'name' => 'Refahiye','city_id' => 24),
            array('id' => 751,'name' => 'Reşadiye','city_id' => 60),
            array('id' => 752,'name' => 'Reyhanlı','city_id' => 31),
            array('id' => 753,'name' => 'Rize','city_id' => 53),
            array('id' => 754,'name' => 'Safranbolu','city_id' => 78),
            array('id' => 755,'name' => 'Saimbeyli','city_id' => 1),
            array('id' => 756,'name' => 'Salıpazarı','city_id' => 55),
            array('id' => 757,'name' => 'Salihli','city_id' => 45),
            array('id' => 758,'name' => 'Samandağ','city_id' => 31),
            array('id' => 759,'name' => 'Samsat','city_id' => 2),
            array('id' => 760,'name' => 'Sancaktepe','city_id' => 34),
            array('id' => 761,'name' => 'Sandıklı','city_id' => 3),
            array('id' => 762,'name' => 'Sapanca','city_id' => 54),
            array('id' => 763,'name' => 'Saray','city_id' => 59),
            array('id' => 764,'name' => 'Saray','city_id' => 65),
            array('id' => 765,'name' => 'Saraydüzü','city_id' => 57),
            array('id' => 766,'name' => 'Saraykent','city_id' => 66),
            array('id' => 767,'name' => 'Sarayköy','city_id' => 20),
            array('id' => 768,'name' => 'Sarayönü','city_id' => 42),
            array('id' => 769,'name' => 'Sarıcakaya','city_id' => 26),
            array('id' => 770,'name' => 'Sarıçam','city_id' => 1),
            array('id' => 771,'name' => 'Sarıgöl','city_id' => 45),
            array('id' => 772,'name' => 'Sarıkamış','city_id' => 36),
            array('id' => 773,'name' => 'Sarıkaya','city_id' => 66),
            array('id' => 774,'name' => 'Sarıoğlan','city_id' => 38),
            array('id' => 775,'name' => 'Sarıveliler','city_id' => 70),
            array('id' => 776,'name' => 'Sarıyahşi','city_id' => 68),
            array('id' => 777,'name' => 'Sarıyer','city_id' => 34),
            array('id' => 778,'name' => 'Sarız','city_id' => 38),
            array('id' => 779,'name' => 'Saruhanlı','city_id' => 45),
            array('id' => 780,'name' => 'Sason','city_id' => 72),
            array('id' => 781,'name' => 'Savaştepe','city_id' => 10),
            array('id' => 782,'name' => 'Savur','city_id' => 47),
            array('id' => 783,'name' => 'Seben','city_id' => 14),
            array('id' => 784,'name' => 'Seferihisar','city_id' => 35),
            array('id' => 785,'name' => 'Selçuk','city_id' => 35),
            array('id' => 786,'name' => 'Selçuklu','city_id' => 42),
            array('id' => 787,'name' => 'Selendi','city_id' => 45),
            array('id' => 788,'name' => 'Selim','city_id' => 36),
            array('id' => 789,'name' => 'Senirkent','city_id' => 32),
            array('id' => 790,'name' => 'Serdivan','city_id' => 54),
            array('id' => 791,'name' => 'Serik','city_id' => 7),
            array('id' => 792,'name' => 'Serinhisar','city_id' => 20),
            array('id' => 793,'name' => 'Seydikemer','city_id' => 48),
            array('id' => 794,'name' => 'Seydiler','city_id' => 37),
            array('id' => 795,'name' => 'Seydişehir','city_id' => 42),
            array('id' => 796,'name' => 'Seyhan','city_id' => 1),
            array('id' => 797,'name' => 'Seyitgazi','city_id' => 26),
            array('id' => 798,'name' => 'Sındırgı','city_id' => 10),
            array('id' => 799,'name' => 'Siirt','city_id' => 56),
            array('id' => 800,'name' => 'Silifke','city_id' => 33),
            array('id' => 801,'name' => 'Silivri','city_id' => 34),
            array('id' => 802,'name' => 'Silopi','city_id' => 73),
            array('id' => 803,'name' => 'Silvan','city_id' => 21),
            array('id' => 804,'name' => 'Simav','city_id' => 43),
            array('id' => 805,'name' => 'Sinanpaşa','city_id' => 3),
            array('id' => 806,'name' => 'Sincan','city_id' => 6),
            array('id' => 807,'name' => 'Sincik','city_id' => 2),
            array('id' => 808,'name' => 'Sinop','city_id' => 57),
            array('id' => 809,'name' => 'Sivas','city_id' => 58),
            array('id' => 810,'name' => 'Sivaslı','city_id' => 64),
            array('id' => 811,'name' => 'Siverek','city_id' => 63),
            array('id' => 812,'name' => 'Sivrice','city_id' => 23),
            array('id' => 813,'name' => 'Sivrihisar','city_id' => 26),
            array('id' => 814,'name' => 'Solhan','city_id' => 12),
            array('id' => 815,'name' => 'Soma','city_id' => 45),
            array('id' => 816,'name' => 'Sorgun','city_id' => 66),
            array('id' => 817,'name' => 'Söğüt','city_id' => 11),
            array('id' => 818,'name' => 'Söğütlü','city_id' => 54),
            array('id' => 819,'name' => 'Söke','city_id' => 9),
            array('id' => 820,'name' => 'Sulakyurt','city_id' => 71),
            array('id' => 821,'name' => 'Sultanbeyli','city_id' => 34),
            array('id' => 822,'name' => 'Sultandağı','city_id' => 3),
            array('id' => 823,'name' => 'Sultangazi','city_id' => 34),
            array('id' => 824,'name' => 'Sultanhisar','city_id' => 9),
            array('id' => 825,'name' => 'Suluova','city_id' => 5),
            array('id' => 826,'name' => 'Sulusaray','city_id' => 60),
            array('id' => 827,'name' => 'Sumbas','city_id' => 80),
            array('id' => 828,'name' => 'Sungurlu','city_id' => 19),
            array('id' => 829,'name' => 'Sur','city_id' => 21),
            array('id' => 830,'name' => 'Suruç','city_id' => 63),
            array('id' => 831,'name' => 'Susurluk','city_id' => 10),
            array('id' => 832,'name' => 'Susuz','city_id' => 36),
            array('id' => 833,'name' => 'Suşehri','city_id' => 58),
            array('id' => 834,'name' => 'Süleymanpaşa','city_id' => 59),
            array('id' => 835,'name' => 'Süloğlu','city_id' => 22),
            array('id' => 836,'name' => 'Sürmene','city_id' => 61),
            array('id' => 837,'name' => 'Sütçüler','city_id' => 32),
            array('id' => 838,'name' => 'Şabanözü','city_id' => 18),
            array('id' => 839,'name' => 'Şahinbey','city_id' => 27),
            array('id' => 840,'name' => 'Şalpazarı','city_id' => 61),
            array('id' => 841,'name' => 'Şaphane','city_id' => 43),
            array('id' => 842,'name' => 'Şarkışla','city_id' => 58),
            array('id' => 843,'name' => 'Şarkikaraağaç','city_id' => 32),
            array('id' => 844,'name' => 'Şarköy','city_id' => 59),
            array('id' => 845,'name' => 'Şavşat','city_id' => 8),
            array('id' => 846,'name' => 'Şebinkarahisar','city_id' => 28),
            array('id' => 847,'name' => 'Şefaatli','city_id' => 66),
            array('id' => 848,'name' => 'Şehitkamil','city_id' => 27),
            array('id' => 849,'name' => 'Şehzadeler','city_id' => 45),
            array('id' => 850,'name' => 'Şemdinli','city_id' => 30),
            array('id' => 851,'name' => 'Şenkaya','city_id' => 25),
            array('id' => 852,'name' => 'Şenpazar','city_id' => 37),
            array('id' => 853,'name' => 'Şereflikoçhisar','city_id' => 6),
            array('id' => 854,'name' => 'Şırnak','city_id' => 73),
            array('id' => 855,'name' => 'Şile','city_id' => 34),
            array('id' => 856,'name' => 'Şiran','city_id' => 29),
            array('id' => 857,'name' => 'Şirvan','city_id' => 56),
            array('id' => 858,'name' => 'Şişli','city_id' => 34),
            array('id' => 859,'name' => 'Şuhut','city_id' => 3),
            array('id' => 860,'name' => 'Talas','city_id' => 38),
            array('id' => 861,'name' => 'Taraklı','city_id' => 54),
            array('id' => 862,'name' => 'Tarsus','city_id' => 33),
            array('id' => 863,'name' => 'Taşkent','city_id' => 42),
            array('id' => 864,'name' => 'Taşköprü','city_id' => 37),
            array('id' => 865,'name' => 'Taşlıçay','city_id' => 4),
            array('id' => 866,'name' => 'Taşova','city_id' => 5),
            array('id' => 867,'name' => 'Tatvan','city_id' => 13),
            array('id' => 868,'name' => 'Tavas','city_id' => 20),
            array('id' => 869,'name' => 'Tavşanlı','city_id' => 43),
            array('id' => 870,'name' => 'Tefenni','city_id' => 15),
            array('id' => 871,'name' => 'Tekkeköy','city_id' => 55),
            array('id' => 872,'name' => 'Tekman','city_id' => 25),
            array('id' => 873,'name' => 'Tepebaşı','city_id' => 26),
            array('id' => 874,'name' => 'Tercan','city_id' => 24),
            array('id' => 875,'name' => 'Termal','city_id' => 77),
            array('id' => 876,'name' => 'Terme','city_id' => 55),
            array('id' => 877,'name' => 'Tillo','city_id' => 56),
            array('id' => 878,'name' => 'Tire','city_id' => 35),
            array('id' => 879,'name' => 'Tirebolu','city_id' => 28),
            array('id' => 880,'name' => 'Tokat','city_id' => 60),
            array('id' => 881,'name' => 'Tomarza','city_id' => 38),
            array('id' => 882,'name' => 'Tonya','city_id' => 61),
            array('id' => 883,'name' => 'Toprakkale','city_id' => 80),
            array('id' => 884,'name' => 'Torbalı','city_id' => 35),
            array('id' => 885,'name' => 'Toroslar','city_id' => 33),
            array('id' => 886,'name' => 'Tortum','city_id' => 25),
            array('id' => 887,'name' => 'Torul','city_id' => 29),
            array('id' => 888,'name' => 'Tosya','city_id' => 37),
            array('id' => 889,'name' => 'Tufanbeyli','city_id' => 1),
            array('id' => 890,'name' => 'Tunceli','city_id' => 62),
            array('id' => 891,'name' => 'Turgutlu','city_id' => 45),
            array('id' => 892,'name' => 'Turhal','city_id' => 60),
            array('id' => 893,'name' => 'Tuşba','city_id' => 65),
            array('id' => 894,'name' => 'Tut','city_id' => 2),
            array('id' => 895,'name' => 'Tutak','city_id' => 4),
            array('id' => 896,'name' => 'Tuzla','city_id' => 34),
            array('id' => 897,'name' => 'Tuzluca','city_id' => 76),
            array('id' => 898,'name' => 'Tuzlukçu','city_id' => 42),
            array('id' => 899,'name' => 'Türkeli','city_id' => 57),
            array('id' => 900,'name' => 'Türkoğlu','city_id' => 46),
            array('id' => 901,'name' => 'Uğurludağ','city_id' => 19),
            array('id' => 902,'name' => 'Ula','city_id' => 48),
            array('id' => 903,'name' => 'Ulaş','city_id' => 58),
            array('id' => 904,'name' => 'Ulubey','city_id' => 52),
            array('id' => 905,'name' => 'Ulubey','city_id' => 64),
            array('id' => 906,'name' => 'Uluborlu','city_id' => 32),
            array('id' => 907,'name' => 'Uludere','city_id' => 73),
            array('id' => 908,'name' => 'Ulukışla','city_id' => 51),
            array('id' => 909,'name' => 'Ulus','city_id' => 74),
            array('id' => 910,'name' => 'Urla','city_id' => 35),
            array('id' => 911,'name' => 'Uşak','city_id' => 64),
            array('id' => 912,'name' => 'Uzundere','city_id' => 25),
            array('id' => 913,'name' => 'Uzunköprü','city_id' => 22),
            array('id' => 914,'name' => 'Ümraniye','city_id' => 34),
            array('id' => 915,'name' => 'Ünye','city_id' => 52),
            array('id' => 916,'name' => 'Ürgüp','city_id' => 50),
            array('id' => 917,'name' => 'Üsküdar','city_id' => 34),
            array('id' => 918,'name' => 'Üzümlü','city_id' => 24),
            array('id' => 919,'name' => 'Vakfıkebir','city_id' => 61),
            array('id' => 920,'name' => 'Varto','city_id' => 49),
            array('id' => 921,'name' => 'Vezirköprü','city_id' => 55),
            array('id' => 922,'name' => 'Viranşehir','city_id' => 63),
            array('id' => 923,'name' => 'Vize','city_id' => 39),
            array('id' => 924,'name' => 'Yağlıdere','city_id' => 28),
            array('id' => 925,'name' => 'Yahşihan','city_id' => 71),
            array('id' => 926,'name' => 'Yahyalı','city_id' => 38),
            array('id' => 927,'name' => 'Yakakent','city_id' => 55),
            array('id' => 928,'name' => 'Yakutiye','city_id' => 25),
            array('id' => 929,'name' => 'Yalıhüyük','city_id' => 42),
            array('id' => 930,'name' => 'Yalova','city_id' => 77),
            array('id' => 931,'name' => 'Yalvaç','city_id' => 32),
            array('id' => 932,'name' => 'Yapraklı','city_id' => 18),
            array('id' => 933,'name' => 'Yatağan','city_id' => 48),
            array('id' => 934,'name' => 'Yavuzeli','city_id' => 27),
            array('id' => 935,'name' => 'Yayladağı','city_id' => 31),
            array('id' => 936,'name' => 'Yayladere','city_id' => 12),
            array('id' => 937,'name' => 'Yazıhan','city_id' => 44),
            array('id' => 938,'name' => 'Yedisu','city_id' => 12),
            array('id' => 939,'name' => 'Yenice','city_id' => 17),
            array('id' => 940,'name' => 'Yenice','city_id' => 78),
            array('id' => 941,'name' => 'Yeniçağa','city_id' => 14),
            array('id' => 942,'name' => 'Yenifakılı','city_id' => 66),
            array('id' => 943,'name' => 'Yenimahalle','city_id' => 6),
            array('id' => 944,'name' => 'Yenipazar','city_id' => 9),
            array('id' => 945,'name' => 'Yenipazar','city_id' => 11),
            array('id' => 946,'name' => 'Yenişarbademli','city_id' => 32),
            array('id' => 947,'name' => 'Yenişehir','city_id' => 16),
            array('id' => 948,'name' => 'Yenişehir','city_id' => 21),
            array('id' => 949,'name' => 'Yenişehir','city_id' => 33),
            array('id' => 950,'name' => 'Yerköy','city_id' => 66),
            array('id' => 951,'name' => 'Yeşilhisar','city_id' => 38),
            array('id' => 952,'name' => 'Yeşilli','city_id' => 47),
            array('id' => 953,'name' => 'Yeşilova','city_id' => 15),
            array('id' => 954,'name' => 'Yeşilyurt','city_id' => 44),
            array('id' => 955,'name' => 'Yeşilyurt','city_id' => 60),
            array('id' => 956,'name' => 'Yığılca','city_id' => 81),
            array('id' => 957,'name' => 'Yıldırım','city_id' => 16),
            array('id' => 958,'name' => 'Yıldızeli','city_id' => 58),
            array('id' => 959,'name' => 'Yomra','city_id' => 61),
            array('id' => 960,'name' => 'Yozgat','city_id' => 66),
            array('id' => 961,'name' => 'Yumurtalık','city_id' => 1),
            array('id' => 962,'name' => 'Yunak','city_id' => 42),
            array('id' => 963,'name' => 'Yunusemre','city_id' => 45),
            array('id' => 964,'name' => 'Yusufeli','city_id' => 8),
            array('id' => 965,'name' => 'Yüksekova','city_id' => 30),
            array('id' => 966,'name' => 'Yüreğir','city_id' => 1),
            array('id' => 967,'name' => 'Zara','city_id' => 58),
            array('id' => 968,'name' => 'Zeytinburnu','city_id' => 34),
            array('id' => 969,'name' => 'Zile','city_id' => 60),
            array('id' => 970,'name' => 'Zonguldak','city_id' => 67),
            array('id' => 971,'name' => 'Kemalpaşa','city_id' => 8),
            array('id' => 972,'name' => 'Sultanhanı','city_id' => 68)
                  ]);
    }
}
